# use Ganache's forked mainnet mode as the default network
networks:
  default: development

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"

reports:
  exclude_paths:
    - contracts/mock/ERC20Token.sol
    - contracts/mock/MockStrategy.sol
    - contracts/mock/StrategyCurveYVoterProxyAbstract.sol
  exclude_contracts:
    - SafeMath
